---

version: "3"

services:
  nodejs:
    image: hyuio0228/frontend:yarnadd
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    container_name: frontend
    entrypoint: yarn start

---
