name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: psf/black@stable
        with:
          options: "--verbose"
          src: "."
          jupyter: true
          version: "21.5b1"
